### PR TITLE
Reading assignment

### PR DESCRIPTION
**Pull request by glouppe**
CC: @epochstamp @AWehenkel 

Shall we be more specific? e.g. with precise questions to answer? 

(I think it is fine like this, as the main goal is rather to introduce them to reading scientific papers.)

### CODE REVIEW

**Comment by glouppe** [comment]
Shall we also impose a template?

**Comment by AWehenkel** [comment]
I would say yes for the template. Nips? AIstat?

**Comment by AWehenkel** [comment]
About the questions, I think it's enough like that.

**Comment by glouppe** [comment]
Thanks Antoine! I added instructions for the template.

**Pull request merged**
