### PR TITLE
Pacman Project P2 branch

### PR DESCRIPTION
**Pull request by epochstamp**
open a new branch due to sync issues with master, include instructions for project part 2 and address the remarks in the pull request on the old branch pacman_project_2.

### CODE REVIEW

**Comment by epochstamp** [comment]
I have implemented minimax and tested it on the 'small_adv' maze. It works but it requires the following : 
 - The graph exploration is subject to cycles. A good implementation of minimax in this case needs to (i) prevent cycles, and returns something relevant when the exploration is stuck at some node (this should be avoided by the pacman agent, so I chose to highly penalize this case) and (ii) to keep a transposition table to avoid to compute several times the same score (it computes forever if I don't add that feature).

So, as long as the students figure out to prevent and to carefully process the cycle case, it may be quickly implemented (couple of days). Also, I designed the map to make pacman win but if you move the initial ghost position somewhere else, Pacman may decide to die quickly, and this is normal behavior since the agent assumes that the ghost strategy is optimal. 

People usually don't do this and prefers to limit the depth. But this is something that is more relevant to do in H-Minimax in our project.

Now I'm trying to design the medium adversial maze. I'll keep you informed ASAP.

**Comment by glouppe** [comment]
Any update? We should have the project ready and polished for this Thursday.

**Comment by epochstamp** [comment]
My implementation of Minimax seems to work on small and medium layouts (just uploaded a new version of the medium layout). What I have to add with transposition table and cycle avoidance is to not allow ghost to choose to put pac-man in a cycle if there is an alternative.

Minimax won't work in the large layout, and I don't expect students to manage to do so, it is normal. The goal here is to see how h-alphabeta is more efficient compared to minimax and alphabeta in the small and the medium layouts, and how it manages to address the large layout whereas the minimax and (maybe) the alpha beta won't. 
Maybe we should add something in the instructions to tell them that minimax *has* to work on small and medium layouts but not in large ?

(All the hacks they want to do to address the large maze are supposed to be done either in alphabeta (state ordering for early cutoffs) or in h-alphabeta (good cutoff heuristic))

**Comment by glouppe** [comment]
Indeed, we should not expect minimax, even with alpha-beta pruning, to work quite well. But the small maps should be designed such that they at least can be solved.

I'll add some comments in the instructions.

**Comment by glouppe** [comment]
Instructions are now updated. Tell me what you think.

**Comment by AWehenkel** [comment]
It seems good to me.

**Comment by epochstamp** [comment]
It seems good to me as well.

**Comment by glouppe** [comment]
I am merging this. In case of further changes, put the fixes directly in master.

**Pull request merged**
